title: Coding With Chip - Blog
description: Ciprian Turcu's blog.AI scripts, stories, updates text format, with updated code and documentation
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
