title: Coding With Chip - Blog
description: The scripts from the youtube channel and more, in text format, with updated code and documentation
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/' 
  sort_field: 'date'
  sort_reverse: true

