title: Coding With Chip - Blog
description: Ciprian Turcu's blog.AI scripts, ML Models, stories and updates in text format.
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
