title: Coding With Chip - Blog
description: The scripts from the youtube channel and more, in text format, with updated code and documentation
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
